version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - libclang-14-dev

sphinx:
  builder: html
  configuration: doc/conf.py

python:
  install:
    - requirements: requirements.txt
