# Copyright (C) 2024 Daniel Page <dan@phoo.org>
#
# Use of this source code is restricted per the MIT license, a copy of which 
# can be found via https://opensource.org/license/mit (and which is included 
# as LICENSE.txt within the associated archive or repository).

# =============================================================================

build :
	@sphinx-build -M  html ${CURDIR} ${FIAT_PATH_BUILD}/doc

clean :
	@sphinx-build -M clean ${CURDIR} ${FIAT_PATH_BUILD}/doc

# =============================================================================
