# Copyright (C) 2024 Daniel Page <dan@phoo.org>
#
# Use of this source code is restricted per the MIT license, a copy of which 
# can be found via https://opensource.org/license/mit (and which is included 
# as LICENSE.txt within the associated archive or repository).

ifndef REPO_HOME
  $(error "execute 'source ./bin/conf.sh' to configure environment")
endif
ifndef REPO_VERSION
  $(error "execute 'source ./bin/conf.sh' to configure environment")
endif

# =============================================================================

build :
	@sphinx-build -M  html ${CURDIR} ${REPO_HOME}/build/doc

clean :
	@sphinx-build -M clean ${CURDIR} ${REPO_HOME}/build/doc

# =============================================================================
